## ***NUMPY ASSIGMENT***

**Numpy Array Create & Types**

In [8]:
import numpy as np
a = np.arange(0,21)
print(a)
print(a[6:13])
print(a[-3:])
print(a[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12]
[18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


**Numpy Dimmension & Shapes**

In [15]:
import numpy as np
J = np.array([
    [
        [10,11,12],
        [13,14,15],
        [16,17,18],
    ],
    [
        [20,21,22],
        [23,24,25],
        [26,27,28],
    ],
    [
        [30,31,32],
        [33,34,35],
        [36,37,38],
    ]
])
print(J)
print(J.ndim)
print(J.shape)
print(J.size)
print(J.dtype)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]
3
(3, 3, 3)
27
int64


**NUMPY INDEXING SLICING**

In [19]:
import numpy as np
A = np.array([
    ["Denis","Scratch",8],
    ["Frank","Python",18],
    ["Roger","Unity",15]
])
print(A[0], A[1], A[2])
print(A[:,0])
print(A[:,1])
print(A[:,2])
A[0, 1] = "Roblox"
print(A)

['Denis' 'Scratch' '8'] ['Frank' 'Python' '18'] ['Roger' 'Unity' '15']
['Denis' 'Frank' 'Roger']
['Scratch' 'Python' 'Unity']
['8' '18' '15']
[['Denis' 'Roblox' '8']
 ['Frank' 'Python' '18']
 ['Roger' 'Unity' '15']]


**Numpy Operations**

In [35]:
import numpy as np

N = np.array([
    [1, "Januari", 4799],
    [2, "Februari", 3154],
    [3, "Maret", 4238],
    [4, "April", 2929],
    [5, "Mei", 1615]
], dtype=object)  # dtype=object is used to handle mixed types

print(N[:, 2].sum(axis=0))
print(N[:, 2].mean(axis=0))
print(N[:, 2]*2)
N[:,2] = 5000
print(N)

16735
3347.0
[9598 6308 8476 5858 3230]
[[1 'Januari' 5000]
 [2 'Februari' 5000]
 [3 'Maret' 5000]
 [4 'April' 5000]
 [5 'Mei' 5000]]


**Numpy Operation & Bool**

In [42]:
# make it randint 100 - 1000
A = np.random.randint(100, 1000, size=(4,4))

print(A)
print(A[A>500])
B = (A>200)
C = (A<550)
D = (B & C)
print(A[D])

[[119 535 390 583]
 [504 912 360 513]
 [839 780 877 186]
 [839 774 166 290]]
[535 583 504 912 513 839 780 877 839 774]
[535 390 504 360 513 290]


**MINI PROJECT NUMPY CALCULATOR**

In [47]:
import numpy as np

def input_array(prompt):
    user_input = input(prompt)
    return np.array([int(x) for x in user_input.split()])

def calculate_stats(array):
    return array.sum(), array.std(), array.var()

def add_arrays(array1, array2):
    return array1 + array2

def multiply_arrays(array1, array2):
    return array1 * array2

array1 = input_array("Masukan Elements Pertama 1D array dipisahkan spasi: ")
array2 = input_array("Masukan Elements Pertama 1D array dipisahkan spasi: ")

print(array1)
print(array2)
print(add_arrays(array1, array2))
print(multiply_arrays(array1, array2))
print(calculate_stats(array1))
print(calculate_stats(array2))

Masukan Elements Pertama 1D array dipisahkan spasi: 1 2 3
Masukan Elements Pertama 1D array dipisahkan spasi: 9 8 7
[1 2 3]
[9 8 7]
[10 10 10]
(6, 0.816496580927726, 0.6666666666666666)
(24, 0.816496580927726, 0.6666666666666666)


In [ ]:
import numpy as np

# Mendefinisikan fungsi untuk mengambil input dua array
def input_array():
    n = int(input("Masukkan jumlah elemen untuk kedua array: "))
    
    # Input untuk array pertama
    array1 = []
    print(f"Masukkan {n} elemen untuk array pertama:")
    for i in range(n):
        elemen = int(input(f"Elemen {i+1}: "))
        array1.append(elemen)
    np_1 = np.array(array1)
    
    # Input untuk array kedua
    array2 = []
    print(f"Masukkan {n} elemen untuk array kedua:")
    for i in range(n):
        elemen = int(input(f"Elemen {i+1}: "))
        array2.append(elemen)
    np_2 = np.array(array2)
    return np_1, np_2

# Memanggil fungsi dan mencetak hasil
np_1, np_2 = input_array()
print("Array pertama:", np_1)
print("Array kedua:", np_2)
