**NUMPY INTRODUCTION**


NUMPY MENYIMPAN 1 jenis type data
tidak seperti var python yang sebagai objek

In [31]:
import numpy as np

# Membuat array dengan campuran int dan string
arr = np.array([1, 12, 3.14])

# Menampilkan array dan tipe datanya
print(arr)
print(arr.dtype)


[ 1.   12.    3.14]
float64


In [32]:
import numpy as np

# Membuat array dari string
arr = np.array(["apple", "banana", "cherry"])

# Menampilkan array dan tipe datanya
print(arr)
print(arr.dtype)


['apple' 'banana' 'cherry']
<U6


In [33]:
import numpy as np

# Membuat array dengan campuran int dan string
arr = np.array([1, "banana", 3.14])

# Menampilkan array dan tipe datanya
print(arr)
print(arr.dtype)

for member in arr:
  print(member)

['1' 'banana' '3.14']
<U32
1
banana
3.14


**NP ARRAGE DAN SLICING**


In [34]:
import numpy as np

# Membuat array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Mengambil elemen dari indeks 2 hingga 5
slice1 = arr[2:6]
print(slice1)  # Output: [30 40 50 60]

# Mengambil elemen dari indeks 1 hingga 8 dengan langkah 2
slice2 = arr[1:8:2]
print(slice2)  # Output: [20 40 60 80]

# Mengambil elemen dari awal hingga indeks 4
slice3 = arr[:5]
print(slice3)  # Output: [10 20 30 40 50]

# Mengambil elemen dari indeks 5 hingga akhir
slice4 = arr[5:]
print(slice4)  # Output: [60 70 80 90 100]

# Membalik array dengan slicing
slice5 = arr[::-1]
print(slice5)  # Output: [100  90  80  70  60  50  40  30  20  10]


[30 40 50 60]
[20 40 60 80]
[10 20 30 40 50]
[ 60  70  80  90 100]
[100  90  80  70  60  50  40  30  20  10]


**NP DIMENSION DAN SHAPES**

In [35]:
import numpy as np

arr1 = np.array([1, 2, 3])             # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])    # 2D array
arr3 = np.array([[[1], [2]], [[3], [4]]])  # 3D array

print(arr1.shape)  # Output: (3,)
print(arr2.shape)  # Output: (2, 3)
print(arr3.shape)  # Output: (2, 2, 1)


(3,)
(2, 3)
(2, 2, 1)


In [36]:
import numpy as np

# Membuat array 3D
data = np.random.randint(1, 10, size=(3, 2, 4))  # 3 lapisan, 2 baris, 4 kolom

print(f"Array: \n{data}")
print(f"Size: {data.size}")  # Output: 24 (3*2*4)
print(f"Number of Dimensions (ndim): {data.ndim}")  # Output: 3
print(f"Shape: {data.shape}")  # Output: (3, 2, 4)


Array: 
[[[2 1 7 5]
  [8 2 6 1]]

 [[3 9 2 4]
  [7 4 4 2]]

 [[7 5 5 8]
  [9 2 6 3]]]
Size: 24
Number of Dimensions (ndim): 3
Shape: (3, 2, 4)


**NUMPY SLICING ARRAYS AND ASSIGNING**

In [37]:
import numpy as np

# Membuat array 3x3
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Array 3x3:")
print(arr)
cols_0_2 = arr[:, [0, 2]]
print("\nKolom Pertama dan Ketiga:")
print(cols_0_2)
col_1_take = np.take(arr, indices=1, axis=1)
print("\nKolom Kedua dengan np.take():")
print(col_1_take)
print("\nGanti Baris indeks ke 2:")
arr[2] = 10
print(arr)
print("\nGanti Baris indeks ke 1:")
arr[1] = [-1,-2,-3]
print(arr)

Array 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kolom Pertama dan Ketiga:
[[1 3]
 [4 6]
 [7 9]]

Kolom Kedua dengan np.take():
[2 5 8]

Ganti Baris indeks ke 2:
[[ 1  2  3]
 [ 4  5  6]
 [10 10 10]]

Ganti Baris indeks ke 1:
[[ 1  2  3]
 [-1 -2 -3]
 [10 10 10]]


**NP Statistics**

In [38]:
import numpy as np

# Membuat array 2D
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Array 2D:")
print(arr_2d)
mean_all = np.mean(arr_2d)
print("\nRata-rata Seluruh Array:", mean_all)
mean_per_row = np.mean(arr_2d, axis=1)
print("Rata-rata per Baris:", mean_per_row)
mean_per_col = np.mean(arr_2d, axis=0)
print("Rata-rata per Kolom:", mean_per_col)
median_all = np.median(arr_2d)
print("\nMedian Seluruh Array:", median_all)
std_dev_all = np.std(arr_2d)
print("\nStandar Deviasi Seluruh Array:", std_dev_all)
variance_all = np.var(arr_2d)
print("\nVariansi Seluruh Array:", variance_all)
min_all = np.min(arr_2d)
print("\nNilai Minimum Seluruh Array:", min_all)
max_all = np.max(arr_2d)
print("Nilai Maksimum Seluruh Array:", max_all)
sum_all = np.sum(arr_2d)
print("\nPenjumlahan Seluruh Array:", sum_all)


Array 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rata-rata Seluruh Array: 5.0
Rata-rata per Baris: [2. 5. 8.]
Rata-rata per Kolom: [4. 5. 6.]

Median Seluruh Array: 5.0

Standar Deviasi Seluruh Array: 2.581988897471611

Variansi Seluruh Array: 6.666666666666667

Nilai Minimum Seluruh Array: 1
Nilai Maksimum Seluruh Array: 9

Penjumlahan Seluruh Array: 45


**NP LINEAR ALGEBRA**

In [39]:
matrix = np.array([[1, 2], [3, 4]])
transpose_matrix = np.transpose(matrix)
print("Transpose Matriks:")
print(transpose_matrix)
det_matrix = np.linalg.det(matrix)
print("Determinant Matriks:", det_matrix)
inverse_matrix = np.linalg.inv(matrix)
print("Inverse Matriks:")
print(inverse_matrix)



Transpose Matriks:
[[1 3]
 [2 4]]
Determinant Matriks: -2.0000000000000004
Inverse Matriks:
[[-2.   1. ]
 [ 1.5 -0.5]]


**NP OPERASI MATRIKS**

In [40]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

sum_arr = arr + arr2
diff_arr = arr2 - arr
print("Penjumlahan Array:", sum_arr)
print("Pengurangan Array:", diff_arr)
product_arr = arr * arr2
quotient_arr = arr2 / arr
print("Perkalian Array:", product_arr)
print("Pembagian Array:", quotient_arr)
exp_arr = np.exp(arr)
log_arr = np.log(arr)
print("Eksponensial Array:", exp_arr)
print("Logaritma Array:", log_arr)


Penjumlahan Array: [11 22 33 44 55]
Pengurangan Array: [ 9 18 27 36 45]
Perkalian Array: [ 10  40  90 160 250]
Pembagian Array: [10. 10. 10. 10. 10.]
Eksponensial Array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logaritma Array: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


**NP BROADCASTING**

In [41]:
import numpy as np

# Membuat array NumPy 3x3
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Array Asli:")
print(arr_3x3)

# Menambahkan 2 ke kolom ketiga (indeks 2)
arr_3x3[:, 2] = arr_3x3[:, 2] + 2

print("\nArray Setelah Kolom Ketiga Ditambahkan 2:")
print(arr_3x3)

# Mengkurangkan 2
arr_3x3 = arr_3x3 - 2
print("\nArray Setelah Dikurangkan 2:")
print(arr_3x3)

Array Asli:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array Setelah Kolom Ketiga Ditambahkan 2:
[[ 1  2  5]
 [ 4  5  8]
 [ 7  8 11]]

Array Setelah Dikurangkan 2:
[[-1  0  3]
 [ 2  3  6]
 [ 5  6  9]]


**NP BOOLEAN**

In [42]:
import numpy as np

# Membuat array NumPy
arr = np.array([1, 2, 3, 4, 5, 6])

# Kondisi: elemen lebih besar dari 2
condition1 = arr > 2

# Kondisi: elemen kurang dari 5
condition2 = arr < 5

# Menggunakan negasi (not), and, dan or
# Negasi: Membalikkan kondisi (elemen <= 2 atau elemen >= 5)
negated_condition = ~(condition1 & condition2)

# And: Elemen yang lebih besar dari 2 DAN kurang dari 5
and_condition = condition1 & condition2

# Or: Elemen yang lebih besar dari 2 ATAU kurang dari 5
or_condition = condition1 | condition2

# Hasil seleksi dengan kondisi negasi, and, dan or
negated_result = arr[negated_condition]
and_result = arr[and_condition]
or_result = arr[or_condition]

# Menampilkan hasil
print("Array Asli:")
print(arr)

print("\nNegasi (Not): Elemen <= 2 atau >= 5:")
print(negated_result)

print("\nAnd: Elemen > 2 dan < 5:")
print(and_result)

print("\nOr: Elemen > 2 atau < 5:")
print(or_result)


Array Asli:
[1 2 3 4 5 6]

Negasi (Not): Elemen <= 2 atau >= 5:
[1 2 5 6]

And: Elemen > 2 dan < 5:
[3 4]

Or: Elemen > 2 atau < 5:
[1 2 3 4 5 6]
